spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ${mongodb_db}
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohdasha.dev@gmail.com
    password: ${dev_mail_password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: false
server:
  port: 8082
  ssl:
    key-store: classpath:mohdasha.com.p12
    key-store-type: PKCS12
    key-store-password:
    key-alias: mohdasha
logging:
  level:
    org.springframework: INFO